FROM --platform=linux/arm64 python:3.11

# install C++ compiler and cmake
# RUN apt-get update && apt-get install -y \
#    build-essential \
#    cmake \
#    gcc \
#    g++ \
#    && rm -rf /var/lib/apt/lists/*

WORKDIR /rag-app

COPY ./requirements.txt /rag-app/requirements.txt

# docker update pip incase it's old
run pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade -r /rag-app/requirements.txt

COPY  . /rag-app

RUN python3 build_executable.py

CMD python3 run.py